[package]
name = "giraffeduck"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.11.8"
handlebars = "6.3.2"
lazy_static = "1.5.0"
lru = "0.16.0"
minreq = { version = "2.14.0", features = ["https-native"] }
ntex = { version = "2.15.1", features = ["compress", "openssl", "tokio", "url"] }
ntex-files = "2.1.0"
openssl = "0.10.73"
rand = "0.9.2"
serde = { version = "1.0.219", features = ["derive"] }
url = "2.5.4"
