services:
  giraffeduck:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      BIND_TO: '0.0.0.0:8080'
    ports:
      - 8080:8080
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "/app/healthcheck", "http://giraffeduck:8080/healthcheck" ]
      interval: 10s
      timeout: 10s
      retries: 3
    # networks:
    #   - caddy
    labels:
      caddy: 'giraffeduck.com'
      caddy.reverse_proxy: '{{upstreams 8080}}'

# networks:
#   caddy:
#     external: true
