version: '3.7'
services:
  giraffeduck:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      NODE_ENV: production
      GIRAFFEDUCK_PORT: 8080
    env_file:
      - .env
    volumes:
      - ./:/home/node/app
    networks:
      - caddy
    labels:
      caddy: 'giraffeduck.com'
      caddy.reverse_proxy: '{{upstreams 8080}}'

networks:
  caddy:
    external: true
