services:
  giraffeduck:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      BIND_TO: '0.0.0.0:8080'
    ports:
      - 8080:8080
    env_file:
      - .env
    # networks:
    #   - caddy
    labels:
      caddy: 'giraffeduck.com'
      caddy.reverse_proxy: '{{upstreams 8080}}'

# networks:
#   caddy:
#     external: true
